### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by panosmdma** [montagdude/sboui#1]
Hi, I tried to compile the latest snapshot and 0.3.1v but both their failed with:

CMake Error at cmake/Modules/FindLibconfig++.cmake:13 (message):
  Could NOT find libconfig++.h!
Call Stack (most recent call first):
  CMakeLists.txt:46 (find_package)

Tested in Slackware64 and Slackware64-Current.

**Comment by montagdude** [comment]
Hi,

Did you install libconfig? It's available on SBo. I have it listed in the .info file for the SlackBuild, but I should probably put it in README.md and INSTALL also.

**Comment by panosmdma** [comment]
Ooops... Sorry about the noise :( . I was impatient to check it and forgot to check the .info.
