### ISSUE TITLE
How to store *.tar.gz source package alongside *.SlackBuild file

### ISSUE THREAD

**Issue by vitacell** [montagdude/sboui#3]
Hi, need help, don't understand what sboui does, and where it downloads the *.tar.gz source packages. When I install packages with sboui, I want it to store downloaded *.tar.gz source packages alongside *.SlackBuild file, yeah right inside the SlackBuild folder like you do manual download and compiling from https://slackbuilds.org.
I just want to store *.tar.gz source packages inside local sboui's repository, not /tmp/SBo/.

Let's take gpaint, click on install inside sboui:
Here is an example of what I have:

$ /var/lib/sboui/repo/graphics/gpaint/
README	   gpaint.1	      gpaint.desktop  gpaint.png  slack-desc
doinst.sh  gpaint.SlackBuild  gpaint.info     patches

I want this:
$ ls /var/lib/sboui/repo/graphics/gpaint/
README	   gpaint.SlackBuild  gpaint.png		slack-desc
doinst.sh  gpaint.desktop     gpaint_0.3.3.orig.tar.gz
gpaint.1   gpaint.info	      patches

What I want is just to save the downloaded package alongside *.SlackBuild file, in the sboui's repository.

**Comment by montagdude** [comment]
If you are using the default sboui-backend package manager, you can achieve this by commenting out the lines inside the function called remove_sources in the script (/usr/sbin/sboui-backend). In the latest master, this would be lines 341-349. I don't know if the other package managers, sbopkg or sbotools, have an option to do that.

**Comment by vitacell** [comment]
Looks like this works: https://dpaste.com/DP37RPSUS
Thanks you very much for your help. 
Hope you include "do not remove source package" option in your backend's options (obviously disabled by default).

**Comment by montagdude** [comment]
Glad it worked. I will put it on my TODO list.

**Comment by montagdude** [comment]
This option was added in 31d650a00.
