### ISSUE TITLE
Can't get 15.0 branch

### ISSUE THREAD

**Issue by kermitdafrog8** [montagdude/sboui#4]
error: pathspec '15.0' did not match any file(s) known to git

This is the error message I receive when trying to sync with the 15.0 Slackbuild branch.

**Comment by montagdude** [comment]
When switching to a new branch, I had to delete the existing repo first (/var/lib/sboui/repo). Do that and then sync again.

**Comment by kermitdafrog8** [comment]
I did that before but now it's working.  Probably something from upstream.
