### ISSUE TITLE
sboui has won't download source code

### ISSUE THREAD

**Issue by thetibetantr** [montagdude/sboui#5]
On Feb. 4, I upgraded several slackware-15.0 packages and sboui has stopped downloading source packages.   For example, when I try to upgrade 'gtest', I get:

ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert TLS Hybrid ECCSHA384 2020 CA1,O=DigiCert Inc,C=US’:
Unable to locally verify the issuer's authority.

I suspect that this is due to something in the upgraded packages 'curl' or 'openssl'.

**Comment by montagdude** [comment]
Hm, I just upgraded my system and can't reproduce that problem. Are you using the built-in backend, or something else (like sbopkg or sbotools)?

**Comment by montagdude** [comment]
It uses wget. It doesn't do anything on its own regarding certs, so I think this has to be a system issue on your end. You can try `wget source_code_url` on your own and see if that has the same problem.
